import tseslint from "typescript-eslint";
import reactPlugin from "eslint-plugin-react";

export default tseslint.config(
  {
    ignores: [
      "node_modules/",
      "public/",
      ".cache/",
      "src/gatsby-types.d.ts", // autogenerated
    ],
  },
  ...tseslint.configs.recommended,
  // Use the jsx-runtime preset: enables recommended rules + disables react-in-jsx-scope
  // and react/jsx-uses-react (not needed with Gatsby 5 / React 18 automatic JSX transform)
  reactPlugin.configs.flat["jsx-runtime"],
  {
    // TypeScript enforces prop types; disable the runtime check for .ts/.tsx files
    files: ["**/*.{ts,tsx}"],
    settings: { react: { version: "detect" } },
    rules: {
      "react/prop-types": "off",
    },
  },
  {
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
